name: PR Jira Check 

on: [pull_request]
    
jobs:
  JIRA-Check:
    name: "Jira Check"
    runs-on: ubuntu-latest
    steps:
    - uses: mforutan/action-pr-title@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        regex: '((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-\d+)' # Regex the title should match.
#         allowed_prefixes: 'feature,stable,fix' # title should start with the given prefix
#         prefix_case_sensitive: false # title prefix are case insensitive
        min_length: 5 # Min length of the title
#         max_length: 20 # Max length of the title
      
